# -*- coding: utf-8 -*-
"""Homework_R_S_P

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cMHam0HC6ZzpYlhM5Hev4iU_Vm69ViIV
"""

print(paste("Your hand is:",player_weapon))
return(paste("Bot hand is:",bot_weapon))

RRRRRRocplayer_weapon <- readline("Choose your weapon (Rock, Paper,Scissor): ")
if ( !(player_weapon %in% weapon) ) {
        player_weapon <- readline("Choose your weapon again (Rock, Paper,Scissor):")
 }

player_weapon = "Rock"
bot_weapon = "Scissor"

bot_weapon == player_weapon
player_weapon == "Rock"

game <- function() {
    # Intro
    your_name <- readline("What is your name: ")

    print(paste0("Hello ",your_name,", Welcome to the Rock, Scissor, Paper FINAL Tourmament!"))

    print("Let's Start!")

     # weapon!
    weapon <- c("Rock","Paper","Scissor")


    # Set Up Match!
    your_score <- 0
    bot_score <- 0

    while (TRUE) {
        flush.console()
        bot_weapon <- sample(weapon,1)
        player_weapon <- readline("Choose your weapon (Rock, Paper,Scissor or Type 'Exit' to Quit game): ")

        if ( (player_weapon == "Rock") & (bot_weapon == "Scissor" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print("You Win")

            your_score = your_score + 1
        } else if ( (player_weapon == "Rock") & (bot_weapon == "Paper" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print("You Lose")
            bot_score = bot_score + 1

        } else if ( (player_weapon == "Rock") & (bot_weapon == "Rock" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print("Draw")

        } else if ( (player_weapon == "Paper") & (bot_weapon == "Sicssor" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("You Win"))
            your_score = your_score + 1

        } else if ( (player_weapon == "Paper") & (bot_weapon == "Rock" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("You Lose"))
            bot_score = bot_score + 1

        } else if ( (player_weapon == "Paper") & (bot_weapon == "Paper" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("Draw"))

        } else if ( (player_weapon == "Scissor") & (bot_weapon == "Paper" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("You Win"))
            your_score = your_score + 1

        } else if ( (player_weapon == "Scissor") & (bot_weapon == "Rock" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("You Lose"))
            bot_score = bot_score + 1

        } else if ( (player_weapon == "Scissor") & (bot_weapon == "Scissor" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("Draw"))

        } else if ( player_weapon == "Exit") {
            print(paste("Your Score :",your_score))
            print(paste("Bot Score:",bot_score))
            if (your_score > bot_score) {
                print("YOU WIN THE FINAL TOURNAMENT")
                print(paste0(player_name,", You are the NEW CHAMPION OF Rock, Scissor, Paper "))
            } else {
                print("You lose, Try again next time")
            }

            break
        } else {print("Wrong Weapon !")}
    }
}

## Finish
game()

game <- function() {
    # Intro
    your_name <- readline("What is your name: ")

    print(paste0("Hello ",your_name,", Welcome to the Rock, Scissor, Paper FINAL Tourmament!"))

    print("Let's Start!")

     # weapon!
    weapon <- c("Rock","Paper","Scissor")


    # Set Up Match!
    your_score <- 0
    bot_score <- 0

    while (TRUE) {
        #flush.console()
        bot_weapon <- sample(weapon,1)
        player_weapon <- readline("Choose your weapon (Rock, Paper,Scissor or Type 'Exit' to Quit game): ")

        if ( (player_weapon == "Rock") & (bot_weapon == "Scissor" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print("You Win")

            your_score = your_score + 1
        } else if ( (player_weapon == "Rock") & (bot_weapon == "Paper" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print("You Lose")
            bot_score = bot_score + 1

        } else if ( (player_weapon == "Rock") & (bot_weapon == "Rock" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print("Draw")

        } else if ( (player_weapon == "Paper") & (bot_weapon == "Sicssor" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("You Win"))
            your_score = your_score + 1

        } else if ( (player_weapon == "Paper") & (bot_weapon == "Rock" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("You Lose"))
            bot_score = bot_score + 1

        } else if ( (player_weapon == "Paper") & (bot_weapon == "Paper" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("Draw"))

        } else if ( (player_weapon == "Scissor") & (bot_weapon == "Paper" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("You Win"))
            your_score = your_score + 1

        } else if ( (player_weapon == "Scissor") & (bot_weapon == "Rock" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("You Lose"))
            bot_score = bot_score + 1

        } else if ( (player_weapon == "Scissor") & (bot_weapon == "Scissor" )) {
            print(paste("Your weapon is:",player_weapon))
            print(paste("Bot weaapon is:",bot_weapon))
            print(paste("Draw"))

        } else if ( player_weapon == "Exit") {
            print(paste("Your Score :",your_score))
            print(paste("Bot Score:",bot_score))
            if (your_score > bot_score) {
                print("YOU WIN THE FINAL TOURNAMENT")
                print(paste0(player_name,", You are the NEW CHAMPION OF Rock, Scissor, Paper "))
            } else {
                print("You lose, Try again next time")
            }

            break
        } else {print("Wrong Weapon !")}
    }
}

## Finish
game()

